movie/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Administration"
admin.site.index_title = "My administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include("movie_app.urls")),
]

movie_app/urls.py
from django.urls import path
from . import views
from .views import ShowAllActors, ShowDirectorInfo, ShowActorInfo


urlpatterns = [
    path('', views.show_all_movie),
    path('directors', views.show_all_directors),
    path('directors/<slug:slug_director>', ShowDirectorInfo.as_view(), name="director_info"),
    path('actors/', ShowAllActors.as_view()),
    path('actors/<slug:slug_actor>', ShowActorInfo.as_view(), name="actor_info"),
    path('movie/<slug:slug_movie>', views.show_one_movie, name="movie_info"),
]

movie_app/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Director(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    director_email = models.EmailField()
    slug = models.SlugField(default="", null=False, db_index=True)

    def get_url(self):
        return reverse("director_info", args=[self.slug])

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class DressingRoom(models.Model):
    floor = models.IntegerField()
    room = models.IntegerField()

    def __str__(self):
        return f"Этаж {self.floor}, комната {self.room}"



class Actor(models.Model):
    MALE = "M"
    FEMALE = "F"
    GENDERS = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDERS, default="")
    dressing = models.OneToOneField(DressingRoom, on_delete=models.SET_NULL, null=True, blank=True)
    slug = models.SlugField(default="", null=False, db_index=True)

    def get_url(self):
        return reverse("actor_info", args=[self.slug])

    def __str__(self):
        if self.gender == self.MALE:
            return f"Actor - {self.first_name} {self.last_name}"
        return f"Actress - {self.first_name} {self.last_name}"


class Movie(models.Model):
    EUR = "EUR"
    USD = "USD"
    RUB = "RUB"
    CURRENCY_CHOICES = [
        (EUR, 'Euro'),
        (USD, 'Dollar'),
        (RUB, 'Rubles'),
    ]
    name = models.CharField(max_length=40)
    rating = models.IntegerField(validators=[MinValueValidator(1),
                                             MaxValueValidator(100)])
    year = models.IntegerField(null=True, blank=True)
    budget = models.IntegerField(default=1_000_000,
                                 validators=[MinValueValidator(1)])
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=RUB)
    slug = models.SlugField(default="", null=False, db_index=True)
    director = models.ForeignKey(Director, on_delete=models.PROTECT, null=True)
    actors = models.ManyToManyField(Actor)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.name)
    #     super(Movie, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("movie_info", args=[self.slug])

    def __str__(self):
        return f"{self.name} - {self.rating}%"


#  python3 manage.py shell_plus --print-sql

movie_app/views.py
from django.db.models import F, Max, Min, Count, Avg, Value
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

# Create your views here.
from .models import Movie, Director, Actor


def show_all_directors(request):
    directors = sorted(Director.objects.all(), key=lambda director: director.first_name)
    return render(request, "movie_app/all_directors.html", context={
        "directors": directors,
    })


class ShowDirectorInfo(DetailView):
    template_name = "movie_app/director_info.html"
    model = Director
    slug_url_kwarg = 'slug_director'


# def show_director_info(request, slug_director: str):
#     director = get_object_or_404(Director, slug=slug_director)
#     return render(request, "movie_app/director_info.html", context={
#         "director": director,
#     })


class ShowAllActors(ListView):
    template_name = "movie_app/all_actors.html"
    model = Actor
    context_object_name = "actors"


class ShowActorInfo(DetailView):
    template_name = "movie_app/actor_info.html"
    model = Actor
    slug_url_kwarg = 'slug_actor'


# def show_actor_info(request, slug_actor: str):
#     actor = get_object_or_404(Actor, slug=slug_actor)
#     return render(request, "movie_app/actor_info.html", context={
#         "actor": actor,
#     })


def show_all_movie(request):
    # movies = Movie.objects.order_by(F("year").asc(nulls_last=True))
    movies = Movie.objects.annotate(
        true_bool=Value(True),
        false_bool=Value(False),
        new_budget=F("budget") * 1.5,
        rating_year=F("rating") * F("year"),
    )
    agg = movies.aggregate(Avg("budget"), Max("rating"), Min("rating"), Count("id"))
    for movie in movies:
        movie.save()
    return render(request, "movie_app/all_movies.html", {
        "movies": movies,
        "agg": agg,
    })


def show_one_movie(request, slug_movie: str):
    movie = get_object_or_404(Movie, slug=slug_movie)
    return render(request, "movie_app/one_movie.html", {
        "movie": movie,
    })

movie_app/templates/movie_app/actor_info.html
{% extends "movie_app/base.html" %}

{% block title %} {{ actor.first_name }} {{ actor.last_name }}{% endblock %}

{% block content %}
    <h1>Актёр</h1>
    <h2>Имя - {{ actor.first_name }}</h2>
    <h2>Фамилия - {{ actor.last_name }}</h2>
    <hr>
    <h2>Фильмы, в которых снялся актер</h2>
    <ul>
        {% for movie in actor.movie_set.all %}
            <li>{{ movie }}</li>
        {% endfor %}

    </ul>
{% endblock %}

movie_app/templates/movie_app/all_actors.html
{% extends "movie_app/base.html" %}

{% block title %} Все актеры {% endblock %}

{% block content %}
    <h2>Список всех актеров</h2>
    <ul>
        {% for actor in actors %}
            <li><p align="justify"><a
                    href="{{ actor.get_url }}">{{ actor }}</a></p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

movie_app/templates/movie_app/all_directors.html
{% extends "movie_app/base.html" %}

{% block title %} Все фильмы {% endblock %}

{% block content %}
    <h2>Список всех режиссеров</h2>
    <ul>
        {% for director in directors %}
            <li><p align="justify"><a
                    href="{{ director.get_url }}">{{ director.first_name }} {{ director.last_name }}</a></p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

movie_app/templates/movie_app/all_movies.html
{% extends "movie_app/base.html" %}

{% block title %} Все фильмы{% endblock %}

{% block content %}
    <h2>Список всех фильмов</h2>
    <ul>
        {% for movie in movies %}
            <li><p align="justify"> <a href="{{ movie.get_url }}">{{ movie.name }}</a>, рейтинг - {{ movie.rating }}%, год
                - {{ movie.year|default:"Неизвестен" }}, бюджет - {{ movie.budget }}$</p>
            </li>
        {% endfor %}
    </ul>

{#    <h3>Средний бюджет - {{ agg.keys }}</h3>#}
    <h3>Средний бюджет - {{ agg.budget__avg }}</h3>
    <h3>Минимальный рейтинг - {{ agg.rating__min }}</h3>
    <h3>Максимальный рейтинг - {{ agg.rating__max }}</h3>
    <h3>Количество фильмов - {{ agg.id__count }}</h3>
{% endblock %}

movie_app/templates/movie_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% block content %} {% endblock %}
</body>
</html>

movie_app/templates/movie_app/director_info.html
{% extends "movie_app/base.html" %}

{% block title %} {{ director.first_name }} {{ director.last_name }}{% endblock %}

{% block content %}
    <h1>Режиссер</h1>
    <h2>Имя - {{ director.first_name }}</h2>
    <h2>Фамилия - {{ director.last_name }}</h2>
    <h2>E-mail - {{ director.director_email }}</h2>
    <hr>
    <h2>Фильмы, которые снял режиссер</h2>
    <ul>
    {% for movie in director.movie_set.all %}
    <li>{{ movie }}</li>
    {% endfor %}

    </ul>
{% endblock %}

movie_app/templates/movie_app/one_movie.html
{% extends "movie_app/base.html" %}

{% block title %} Информация о фильме {% endblock %}

{% block content %}
    <h2>Информация о фильме  - {{ movie.name }}</h2>
    <h3>Рейтинг - {{ movie.rating }}</h3>
    <h3>Бюджет - {{ movie.budget }}</h3>
    <h3>Год выхода - {{ movie.year|default:"Неизвестен" }}</h3>
    <hr>
    <h2>Режиссер</h2>
    <h3>{{ movie.director.first_name }} {{ movie.director.last_name }}</h3>
    <h3>Электронная почта: {{ movie.director.director_email }}</h3>
    <hr>
    <h2>Список актеров</h2>
    <ul>
    {% for actor in movie.actors.all %}
    <li>{{ actor }}</li>
    {% endfor %}

    </ul>
{% endblock %}